name: esdb-py

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start EventStore
        run: docker-compose up -d
      - name: Install pdm
        run: curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -
      - name: Install deps
        run: pdm install
      - name: Lint
        run: make lint
      - name: Tests
        run:  make test-ci
      - name: Coverage
        uses: codecov/codecov-action@v3
  
